name: bittorrent-tracker
version: master
summary: Simple, robust, BitTorrent tracker
description: |
  Node.js implementation of a BitTorrent tracker, client and server.

apps:
  bittorrent-tracker:
    command: bittorrent-tracker
    plugs: [network, network-bind]

grade: devel
confinement: strict

parts:
  bittorrent-tracker:
    source: .
    plugin: nodejs
